[package]
name = "yaml-split"
version = "0.1.0"
edition = "2021"

[dependencies]
unsafe-libyaml = "0.2"

[dependencies.clap]
version = "3"
default-features = false
features = ["std", "derive", "cargo"]

[profile.release]
lto = true
codegen-units = 1
