---
name: yaml-split Make Branch
on:
  workflow_dispatch: {}
jobs:
  make-branch:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Stuff
      run: |
        set -x
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status
        git remote -v
        branch=make-$(date +%s)
        git checkout -b $branch
        sed -i 's/version = "0.1.8"/version = "0.1.8-make-branch"/' Cargo.toml
        git add Cargo.toml
        git commit -m "Bump the version"
        git push --set-upstream origin $branch
