---
name: yaml-split Make Branch
on:
  workflow_dispatch: {}
jobs:
  make-branch:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Stuff
      run: |
        set -x
        git config --global user.name "Alex Hamlin"
        git config --global user.email github@alexhamlin.co
        git status
        git remote -v
        git checkout -b make-$(date +%s)
        sed -i 's/version = "0.1.8"/version = "0.1.8-make-branch"/' Cargo.toml
        git add Cargo.toml
        git commit -m "Bump the version"
        git push -u origin
