---
name: yaml-split Deep Tests
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  test-linux-msrv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.1
        profile: minimal
    - name: cargo test
      run: cargo test
  test-macos-stable:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: cargo test
      run: cargo test
  test-windows-stable:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: cargo test
      run: cargo test
