---
name: yaml-split main
on:
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test-lint-linux-stable:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install stable --component clippy
        rustup default stable
        rustc --version
    - name: cargo test
      run: cargo +stable test
    - name: cargo clippy
      run: cargo +stable clippy
