---
name: yaml-split Main Tests

on:
  workflow_dispatch: {}
  # push:
  #   branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-lint-linux-stable:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install stable --component clippy
        rustup default stable
        rustc --version
    - name: Test
      run: cargo test
    - name: Clippy
      run: cargo clippy
