---
name: yaml-split Release Process
on:
  workflow_dispatch: {}
env:
  CARGO_TERM_COLOR: always
jobs:
  create-release-branch:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Git user configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Create release branch
      id: create-release
      run: |
        CURRENT_VERSION="$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')"
        [[ ! $CURRENT_VERSION = *-dev ]] && (echo "$CURRENT_VERSION is not a -dev version" && exit 1)

        RELEASE_VERSION="${CURRENT_VERSION%-dev}"
        RELEASE_BRANCH="release/${RELEASE_VERSION}"
        echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        echo "release_branch=$RELEASE_BRANCH" >> "$GITHUB_OUTPUT"

        git checkout -b "release/$RELEASE_VERSION"
        sed -i "s/version = \"${CURRENT_VERSION}\"/version = \"${RELEASE_VERSION}\"/" Cargo.toml
        cargo check
        git add Cargo.toml Cargo.lock
        git commit -m "Release ${RELEASE_VERSION}"
        git push --set-upstream origin "release/$RELEASE_VERSION"
    outputs:
      release_version: ${{ steps.create-release.outputs.release_version }}
      release_branch: ${{ steps.create-release.outputs.release_branch }}

  run-deep-tests:
    needs: create-release-branch
    uses: ./.github/workflows/deep.yml
    with:
      ref: ${{ needs.create-release-branch.outputs.release_branch }}

  build-binaries:
    needs: create-release-branch
    uses: ./.github/workflows/release.yml
    with:
      ref: ${{ needs.create-release-branch.outputs.release_branch }}

  create-tag-and-publish:
    needs:
    - create-release-branch
    - run-deep-tests
    - build-binaries
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.create-release-branch.outputs.release_branch }}
    - name: How are we?
      run: |
          echo "It works!"
