---
name: yaml-split Release
on:
  workflow_dispatch: {}
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
env:
  CARGO_TERM_COLOR: always
jobs:
  build-about:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download cargo-about
      run: |
        version=0.6.2
        slug=cargo-about-$version-x86_64-unknown-linux-musl
        wget https://github.com/EmbarkStudios/cargo-about/releases/download/$version/$slug.tar.gz
        tar -xvf $slug.tar.gz --strip-components=1 $slug/cargo-about
        ./cargo-about generate about.hbs > LICENSES.html
    - name: Upload LICENSES.html
      uses: actions/upload-artifact@v4
      with:
        name: LICENSES.html
        path: LICENSES.html

  build-binaries-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { target: aarch64-unknown-linux-musl,     runner: ubuntu-22.04 }
        - { target: armv7-unknown-linux-musleabihf, runner: ubuntu-22.04 }
        - { target: x86_64-unknown-linux-musl,      runner: ubuntu-22.04 }
        - { target: aarch64-apple-darwin,           runner: macos-14 }
        - { target: x86_64-apple-darwin,            runner: macos-14 }
    runs-on: ${{ matrix.runner }}
    env:
      RUSTFLAGS: -C linker=rust-lld
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
        rustup target add ${{ matrix.target }}
        rustc --version
    - name: Build
      run: |
        cargo build --release --target ${{ matrix.target }}
        gzip -c target/${{ matrix.target }}/release/yaml-split > yaml-split.gz
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: yaml-split-${{ matrix.target }}
        path: yaml-split.gz

  create-release:
    needs: [build-about, build-binaries-unix]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    - name: List Everything
      run: ls -alR
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: |
          **Note:** yaml-split release binaries are built automatically on a
          _best-effort_ basis for a subset of the platforms on which yaml-split
          is tested.

          yaml-split is a silly little program I use to test GitHub Actions for
          Rust projects. There is no formal changelog, nor any serious support.
