---
name: yaml-split Release
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  init-release:
    runs-on: ubuntu-22.04
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: >-
          yaml-split exists for testing purposes only. The binaries in this
          release may or may not work. There is no meaningful changelog.

  build-binaries-unix:
    needs: init-release
    strategy:
      fail-fast: false
      matrix:
        include:
        - { target: aarch64-apple-darwin,           runner: macos-12 }
        - { target: aarch64-unknown-linux-gnu,      runner: ubuntu-22.04 }
        - { target: aarch64-unknown-linux-musl,     runner: ubuntu-22.04 }
        - { target: armv7-unknown-linux-gnueabihf,  runner: ubuntu-22.04 }
        - { target: armv7-unknown-linux-musleabihf, runner: ubuntu-22.04 }
        - { target: x86_64-apple-darwin,            runner: macos-12 }
        - { target: x86_64-unknown-linux-gnu,       runner: ubuntu-22.04 }
        - { target: x86_64-unknown-linux-musl,      runner: ubuntu-22.04 }
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
        rustup target add ${{ matrix.target }}
        rustc --version
    - name: Build
      run: |
        cargo build --release --target ${{ matrix.target }}
        mv target/${{ matrix.target }}/release/yaml-split yaml-split-${{ matrix.target }}
    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: yaml-split-${{ matrix.target }}

  build-binaries-windows:
    needs: init-release
    strategy:
      fail-fast: false
      matrix:
        include:
        - { target: x86_64-pc-windows-msvc,  runner: windows-2022 }
        - { target: aarch64-pc-windows-msvc, runner: windows-2022 }
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
        rustup target add ${{ matrix.target }}
        rustc --version
    - name: Build
      run: |
        cargo build --release --target ${{ matrix.target }}
        move target\${{ matrix.target }}\release\yaml-split.exe yaml-split-${{ matrix.target }}.exe
    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: yaml-split-${{ matrix.target }}.exe
